"""initial_schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_kind'), 'records', ['kind'], unique=False)
    op.create_index(op.f('ix_records_owner_id'), 'records', ['owner_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'plan_id')
    )
    op.create_index(op.f('ix_schedules_next_due'), 'schedules', ['next_due'], unique=False)
    op.create_index(op.f('ix_schedules_owner_id'), 'schedules', ['owner_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_schedules_owner_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_due'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_records_owner_id'), table_name='records')
    op.drop_index(op.f('ix_records_kind'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
