/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_v1_snapshot_get"];
        /** Set Snapshot */
        put: operations["set_snapshot_api_v1_snapshot_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans */
        get: operations["plans_api_v1_plans_get"];
        put?: never;
        /** Add Plan */
        post: operations["add_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Plan */
        patch: operations["change_plan_api_v1_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Observation */
        post: operations["add_observation_api_v1_plans__plan_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transactions */
        get: operations["transactions_api_v1_transactions_get"];
        put?: never;
        /** Add Transaction */
        post: operations["add_transaction_api_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Transactions */
        post: operations["import_transactions_api_v1_transactions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_jobs_get"];
        put?: never;
        /** Add Job */
        post: operations["add_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedules */
        get: operations["schedules_api_v1_schedules_get"];
        put?: never;
        /** Add Schedule */
        post: operations["add_schedule_api_v1_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Schedule */
        delete: operations["remove_schedule_api_v1_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v1_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Erase */
        delete: operations["erase_api_v1_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthView */
        AuthView: {
            user: components["schemas"]["UserView"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** Calculation */
        Calculation: {
            /** Calculation Id */
            calculation_id: string;
            /** Snapshot Hash */
            snapshot_hash: string;
            /** Policy Version */
            policy_version: string;
            /** As Of */
            as_of: string | null;
            /** Evaluated At */
            evaluated_at: string;
            /** Horizon Days */
            horizon_days: number;
            /** Horizon End */
            horizon_end: string;
            /** Currency */
            currency: string;
            /** Basis */
            basis: string;
            /** Assumptions */
            assumptions: string[];
            /** Warnings */
            warnings: string[];
            /** Missing Inputs */
            missing_inputs: string[];
            /** Planned Limit Minor */
            planned_limit_minor: number | null;
            /** Essential Limit Minor */
            essential_limit_minor: number | null;
            /** Essential Headroom Minor */
            essential_headroom_minor: number | null;
            /** Planned Headroom Minor */
            planned_headroom_minor: number | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "CAN" | "CAN_WITH_TRADEOFF" | "CANNOT" | "UNKNOWN";
            /** Candidate Minor */
            candidate_minor: number;
            /** Candidate Date */
            candidate_date: string;
            /** Affected Commitments */
            affected_commitments: string[];
            /** Commitments Beyond Horizon */
            commitments_beyond_horizon: string[];
            /** Excluded Income Ids */
            excluded_income_ids: string[];
            /** Explanation Factors */
            explanation_factors: {
                [key: string]: unknown;
            }[];
        };
        /** Commitment */
        Commitment: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Amount Minor */
            amount_minor: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
        };
        /** Erase */
        Erase: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "DELETE";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Csv Text */
            csv_text: string;
            /**
             * Currency
             * @default EUR
             * @constant
             */
            currency: "EUR";
        };
        /** Income */
        Income: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Amount Minor */
            amount_minor: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** JobCreate */
        JobCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "compare_plan" | "income_search" | "draft_application";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Provider
             * @default manual
             * @enum {string}
             */
            provider: "manual" | "anthropic" | "gemini";
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** JobView */
        JobView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Attempts */
            attempts: number;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** Login */
        Login: {
            /** Password */
            password: string;
        };
        /** MoneySnapshot */
        MoneySnapshot: {
            /** Balance Minor */
            balance_minor?: number | null;
            /**
             * Currency
             * @default EUR
             * @constant
             */
            currency: "EUR";
            /** As Of */
            as_of?: string | null;
            /**
             * Horizon Days
             * @default 30
             */
            horizon_days: number;
            /** Reserve Minor */
            reserve_minor?: number | null;
            /** Goal Minor */
            goal_minor?: number | null;
            /** Living Budget Minor */
            living_budget_minor?: number | null;
            /** Commitments */
            commitments?: components["schemas"]["Commitment"][] | null;
            /** Incomes */
            incomes?: components["schemas"]["Income"][] | null;
            /**
             * Data Complete
             * @default true
             */
            data_complete: boolean;
        };
        /** Observation */
        Observation: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** Page[JobView] */
        Page_JobView_: {
            /** Items */
            items: components["schemas"]["JobView"][];
        };
        /** Page[PlanView] */
        Page_PlanView_: {
            /** Items */
            items: components["schemas"]["PlanView"][];
        };
        /** Page[ScheduleView] */
        Page_ScheduleView_: {
            /** Items */
            items: components["schemas"]["ScheduleView"][];
        };
        /** Page[TransactionView] */
        Page_TransactionView_: {
            /** Items */
            items: components["schemas"]["TransactionView"][];
        };
        /** PlanChange */
        PlanChange: {
            /** Expected Version */
            expected_version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "rejected" | "completed";
            /**
             * Rejection Reason
             * @default
             */
            rejection_reason: string;
        };
        /** PlanCreate */
        PlanCreate: {
            /** Title */
            title: string;
            /**
             * Need
             * @default
             */
            need: string;
            /** Baseline Minor */
            baseline_minor: number;
            /** Alternative Minor */
            alternative_minor: number;
            /** Frequency Per Month */
            frequency_per_month: number;
            /**
             * Setup Cost Minor
             * @default 0
             */
            setup_cost_minor: number;
            /**
             * Currency
             * @default EUR
             * @constant
             */
            currency: "EUR";
        };
        /** PlanView */
        PlanView: {
            /** Title */
            title: string;
            /**
             * Need
             * @default
             */
            need: string;
            /** Baseline Minor */
            baseline_minor: number;
            /** Alternative Minor */
            alternative_minor: number;
            /** Frequency Per Month */
            frequency_per_month: number;
            /**
             * Setup Cost Minor
             * @default 0
             */
            setup_cost_minor: number;
            /**
             * Currency
             * @default EUR
             * @constant
             */
            currency: "EUR";
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "active" | "rejected" | "completed";
            /** Observations */
            observations: components["schemas"]["Observation"][];
            /**
             * Rejection Reason
             * @default
             */
            rejection_reason: string;
            /** Scenario Savings Minor */
            scenario_savings_minor: number;
            /** First Month Savings Minor */
            first_month_savings_minor: number;
            /** Observed Spend Minor */
            observed_spend_minor: number;
            /** Observed Difference Minor */
            observed_difference_minor: number;
        };
        /** ProviderStateView */
        ProviderStateView: {
            /** Items */
            items: components["schemas"]["ProviderView"][];
            /** Metered Inference Enabled */
            metered_inference_enabled: boolean;
            /** Limitations */
            limitations: string[];
            /** Daily Job Limit */
            daily_job_limit: number;
        };
        /** ProviderView */
        ProviderView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Model */
            model?: string | null;
            /** Reason */
            reason?: string | null;
            /** Capabilities */
            capabilities: string[];
        };
        /** ScheduleCreate */
        ScheduleCreate: {
            /** Plan Id */
            plan_id: string;
            /**
             * Interval Hours
             * @default 24
             */
            interval_hours: number;
        };
        /** ScheduleView */
        ScheduleView: {
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** Interval Hours */
            interval_hours: number;
            /** Next Due */
            next_due: number;
        };
        /** Simulation */
        Simulation: {
            /** Amount Minor */
            amount_minor: number;
        };
        /** SnapshotUpdate */
        SnapshotUpdate: {
            /** Expected Version */
            expected_version: number;
            snapshot: components["schemas"]["MoneySnapshot"];
        };
        /** SnapshotView */
        SnapshotView: {
            /** Version */
            version: number;
            snapshot: components["schemas"]["MoneySnapshot"] | null;
            calculation: components["schemas"]["Calculation"] | null;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount Minor */
            amount_minor: number;
            /**
             * Currency
             * @default EUR
             * @constant
             */
            currency: "EUR";
            /** Description */
            description: string;
            /**
             * Category
             * @default uncategorized
             */
            category: string;
            /** External Id */
            external_id?: string | null;
        };
        /** TransactionView */
        TransactionView: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount Minor */
            amount_minor: number;
            /**
             * Currency
             * @default EUR
             * @constant
             */
            currency: "EUR";
            /** Description */
            description: string;
            /**
             * Category
             * @default uncategorized
             */
            category: string;
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
        };
        /** UserView */
        UserView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthView"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_snapshot_api_v1_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotView"];
                };
            };
        };
    };
    set_snapshot_api_v1_snapshot_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_v1_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Simulation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calculation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plans_api_v1_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PlanView_"];
                };
            };
        };
    };
    add_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_plan_api_v1_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_observation_api_v1_plans__plan_id__observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Observation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transactions_api_v1_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TransactionView_"];
                };
            };
        };
    };
    add_transaction_api_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_transactions_api_v1_transactions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobView_"];
                };
            };
        };
    };
    add_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStateView"];
                };
            };
        };
    };
    schedules_api_v1_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ScheduleView_"];
                };
            };
        };
    };
    add_schedule_api_v1_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_schedule_api_v1_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    erase_api_v1_data_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Erase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
